import React, { useState } from 'react';
import { BarChart3, CheckCircle2, FileText, Landmark, LockKeyhole, Send, ShieldCheck } from 'lucide-react';

interface Props { activeTab?: string; membership: any; profile: any; onSignOut: () => void; }

export function GovernmentDashboard({ activeTab = 'notifications', membership, profile, onSignOut }: Props) {
  const partner = membership?.partner;
  const [notice, setNotice] = useState('');
  const [response, setResponse] = useState({ capacity: true, traffic: false, notice: false, stop: false });
  const title = activeTab === 'bookings' ? 'Public mobility evidence' : activeTab === 'profile' ? 'Mandate and access' : 'Coordinated response';
  return <div className="min-h-screen bg-[#03080e] pb-28 text-white">
    <header className="border-b border-white/8 bg-[#050b12]/92 px-5 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><div className="flex items-center gap-3"><Landmark className="h-5 w-5 text-teal-300"/><div><p className="font-black">{partner?.name || 'Public Partner'}</p><p className="text-[9px] font-black uppercase tracking-widest text-teal-300/70">Privacy-safe public coordination</p></div></div><button onClick={onSignOut} className="rounded-xl border border-white/10 px-4 py-2 text-xs font-black text-white/55">Sign out</button></div></header>
    <main className="mx-auto max-w-6xl space-y-6 p-5 sm:p-8"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-teal-300">Public Partner</p><h1 className="mt-2 text-3xl font-black">{title}</h1></div>
    {activeTab === 'notifications' && <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-[2rem] border border-teal-300/15 bg-white/[0.035] p-6"><h2 className="text-xl font-black">Draft response template</h2><p className="mt-2 text-sm text-white/45">No live public situation is selected here. Prepare mandate-permitted actions, then attach them to validated evidence before approval.</p><div className="mt-6 space-y-3">{Object.entries({capacity:'Request operator capacity',traffic:'Coordinate traffic control',notice:'Draft public notice',stop:'Propose temporary stop'}).map(([key,label])=><label key={key} className="flex cursor-pointer items-center gap-3 rounded-2xl border border-white/10 bg-black/20 p-4"><input type="checkbox" checked={(response as any)[key]} onChange={e=>setResponse(v=>({...v,[key]:e.target.checked}))} className="h-4 w-4 accent-teal-400"/><span className="text-sm font-bold">{label}</span></label>)}</div><button onClick={()=>setNotice('Template selection saved locally. Attach validated evidence before requesting approval or publication.')} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-teal-400 text-xs font-black text-slate-950"><Send className="h-4 w-4"/> Save response template</button>{notice&&<p role="status" className="mt-3 text-xs font-bold text-emerald-200">{notice}</p>}</section><aside className="rounded-[2rem] border border-white/10 bg-white/[0.035] p-6"><ShieldCheck className="h-6 w-6 text-teal-300"/><h2 className="mt-4 font-black">Approval boundary</h2><p className="mt-2 text-sm leading-relaxed text-white/45">You may draft and coordinate. A designated public approver must authorize public notices. AFAT Admin permissions remain none.</p><div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-4 text-xs text-white/55">Representative: {profile?.full_name || 'Verified representative'}<br/>Scope: {partner?.mandate_scope || 'Mandate review pending'}</div></aside></div>}
    {activeTab === 'bookings' && <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><BarChart3 className="h-5 w-5 text-teal-300"/><p className="mt-5 text-3xl font-black">—</p><p className="mt-1 text-xs text-white/40">Live corridor baseline</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><CheckCircle2 className="h-5 w-5 text-emerald-300"/><p className="mt-5 text-3xl font-black">0</p><p className="mt-1 text-xs text-white/40">Measured interventions</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><FileText className="h-5 w-5 text-blue-300"/><button onClick={()=>setNotice('Aggregate report preparation started. Personal data is excluded.')} className="mt-5 text-left text-base font-black">Prepare aggregate report →</button></div>{notice&&<p className="sm:col-span-3 text-sm text-emerald-200">{notice}</p>}</section>}
    {activeTab === 'profile' && <section className="grid gap-5 md:grid-cols-2"><div className="rounded-[2rem] border border-teal-300/15 bg-teal-500/8 p-6"><Landmark className="h-6 w-6 text-teal-300"/><h2 className="mt-4 text-xl font-black">{partner?.name || 'Public institution'}</h2><p className="mt-2 text-sm text-white/45">{partner?.jurisdiction || 'Jurisdiction pending'} · {partner?.status || 'under review'}</p></div><div className="rounded-[2rem] border border-white/10 bg-white/[0.035] p-6"><LockKeyhole className="h-6 w-6 text-amber-300"/><h2 className="mt-4 text-xl font-black">Scoped representative</h2><p className="mt-2 text-sm leading-relaxed text-white/45">Aggregated analytics and public intervention drafting only. No citizen PII, operator finances, Planner or Admin powers.</p></div></section>}
    </main>
  </div>;
}
