import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
function keyFromJson(name:string,key:string){try{return JSON.parse(Deno.env.get(name)||"{}")[key]||"";}catch{return "";}}
const ANON=Deno.env.get("SUPABASE_ANON_KEY")||keyFromJson("SUPABASE_PUBLISHABLE_KEYS","default");
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||keyFromJson("SUPABASE_SECRET_KEYS","default");
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
function env(name:string){return (Deno.env.get(name)||"").trim();}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:null;}
function txt(v:unknown){return v==null?"":String(v).trim();}
type Provider="mappls_reference"|"geoapify_reference"|"kakao_maps_reference"|"mapbox_reference";
async function fetchJson(url:string,init?:RequestInit){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const res=await fetch(url,{...init,signal:controller.signal,headers:{"accept":"application/json",...(init?.headers||{})}});const raw=await res.text();let body:any=null;try{body=raw?JSON.parse(raw):null;}catch{body={raw:raw.slice(0,500)}}return {ok:res.ok,status:res.status,body};}finally{clearTimeout(timer);}}
function normalize(provider:Provider,body:any){
 if(provider==="geoapify_reference")return (Array.isArray(body?.features)?body.features:[]).slice(0,8).map((f:any)=>({provider,external_ref:txt(f?.properties?.place_id||f?.properties?.formatted),name:txt(f?.properties?.name||f?.properties?.formatted),address:txt(f?.properties?.formatted),lat:n(f?.properties?.lat??f?.geometry?.coordinates?.[1]),lng:n(f?.properties?.lon??f?.geometry?.coordinates?.[0]),category:txt(f?.properties?.result_type),raw_type:txt(f?.properties?.category)}));
 if(provider==="kakao_maps_reference")return (Array.isArray(body?.documents)?body.documents:[]).slice(0,8).map((d:any)=>({provider,external_ref:txt(d?.id||d?.place_url),name:txt(d?.place_name||d?.address_name),address:txt(d?.road_address_name||d?.address_name),lat:n(d?.y),lng:n(d?.x),category:txt(d?.category_group_name||d?.category_name),distance_m:n(d?.distance)}));
 if(provider==="mapbox_reference")return (Array.isArray(body?.features)?body.features:[]).slice(0,8).map((f:any)=>({provider,external_ref:txt(f?.id||f?.properties?.mapbox_id),name:txt(f?.properties?.name||f?.properties?.full_address||f?.place_name),address:txt(f?.properties?.full_address||f?.properties?.place_formatted||f?.place_name),lat:n(f?.geometry?.coordinates?.[1]),lng:n(f?.geometry?.coordinates?.[0]),category:txt(f?.properties?.feature_type||f?.properties?.poi_category?.[0])}));
 return (Array.isArray(body?.suggestedLocations)?body.suggestedLocations:[]).slice(0,8).map((d:any)=>({provider,external_ref:txt(d?.eLoc||d?.mapplsPin),name:txt(d?.placeName||d?.alternateName),address:txt(d?.placeAddress),lat:n(d?.latitude??d?.lat),lng:n(d?.longitude??d?.lng),category:txt(d?.type),distance_m:n(d?.distance)}));
}
const creds:Record<Provider,{env:string}>={mappls_reference:{env:"MAPPLS_STATIC_KEY"},geoapify_reference:{env:"GEOAPIFY_API_KEY"},kakao_maps_reference:{env:"KAKAO_REST_API_KEY"},mapbox_reference:{env:"MAPBOX_ACCESS_TOKEN"}};
Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return json({error:"POST required"},405);if(!ANON||!SERVICE)return json({error:"Supabase keys unavailable"},500);
 const auth=req.headers.get("authorization")||"";const user=createClient(SUPABASE_URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const service=createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false}});
 const {data:{user:identity}}=await user.auth.getUser();if(!identity)return json({error:"Authenticated AFAT identity required"},401);
 const perms=await Promise.all([user.rpc("afat_has_permission",{p_permission_key:"map.evidence.review",p_company_id:null}),user.rpc("afat_has_permission",{p_permission_key:"planning.aggregate.view",p_company_id:null}),user.rpc("afat_has_permission",{p_permission_key:"system.configure",p_company_id:null})]);if(!perms.some(x=>x.data===true))return json({error:"Source federation authority required"},403);
 const body=await req.json().catch(()=>({}));const action=txt(body.action||"status");
 if(action==="status"){const cityKey=txt(body.city_key||"cm-yaounde").toLowerCase();const {data:city}=await service.from("afat_city_profiles").select("id").eq("city_key",cityKey).eq("status","active").maybeSingle();const providers=(Object.keys(creds) as Provider[]).map(provider=>({provider,credential_env:creds[provider].env,configured:!!env(creds[provider].env)}));if(city){for(const p of providers){await service.from("afat_city_source_plans").update({plan_state:p.configured?"ready":"needs_credentials",last_result:{credential_configured:p.configured,checked_at:new Date().toISOString(),storage_policy:"reference_ephemeral_only"},updated_at:new Date().toISOString()}).eq("city_profile_id",city.id).eq("source_key",p.provider);}}return json({city_key:cityKey,providers});}
 if(action!=="search")return json({error:"action must be status or search"},400);const provider=txt(body.provider) as Provider;if(!(provider in creds))return json({error:"Unsupported provider"},400);const key=env(creds[provider].env);if(!key)return json({error:"Provider credential is not configured",provider},409);const query=txt(body.query).slice(0,160);if(query.length<2)return json({error:"query must contain at least 2 characters"},400);const lat=n(body.lat),lng=n(body.lng);const region=txt(body.region).toUpperCase().slice(0,3);let result:{ok:boolean,status:number,body:any};
 if(provider==="geoapify_reference"){const u=new URL("https://api.geoapify.com/v1/geocode/search");u.searchParams.set("text",query);u.searchParams.set("limit","8");u.searchParams.set("format","geojson");u.searchParams.set("apiKey",key);if(lat!==null&&lng!==null)u.searchParams.set("bias",`proximity:${lng},${lat}`);result=await fetchJson(u.toString());}
 else if(provider==="kakao_maps_reference"){const u=new URL("https://dapi.kakao.com/v2/local/search/keyword.json");u.searchParams.set("query",query);u.searchParams.set("size","8");if(lat!==null&&lng!==null){u.searchParams.set("x",String(lng));u.searchParams.set("y",String(lat));u.searchParams.set("radius","20000");}result=await fetchJson(u.toString(),{headers:{Authorization:`KakaoAK ${key}`}});}
 else if(provider==="mapbox_reference"){const u=new URL("https://api.mapbox.com/search/geocode/v6/forward");u.searchParams.set("q",query);u.searchParams.set("limit","8");u.searchParams.set("access_token",key);if(lat!==null&&lng!==null)u.searchParams.set("proximity",`${lng},${lat}`);result=await fetchJson(u.toString());}
 else{const u=new URL("https://search.mappls.com/search/places/textsearch/json");u.searchParams.set("query",query);u.searchParams.set("access_token",key);if(region)u.searchParams.set("region",region);if(lat!==null&&lng!==null)u.searchParams.set("location",`${lat},${lng}`);result=await fetchJson(u.toString());}
 const normalized=normalize(provider,result.body);const cityKey=txt(body.city_key||"cm-yaounde").toLowerCase();const {data:city}=await service.from("afat_city_profiles").select("id").eq("city_key",cityKey).eq("status","active").maybeSingle();if(city){await service.from("afat_city_source_plans").update({last_run_at:new Date().toISOString(),last_success_at:result.ok?new Date().toISOString():undefined,last_result:{http_status:result.status,result_count:normalized.length,checked_at:new Date().toISOString(),storage_policy:"reference_ephemeral_only"},plan_state:result.ok?"ready":"error",updated_at:new Date().toISOString()}).eq("city_profile_id",city.id).eq("source_key",provider);}
 if(!result.ok)return json({error:"Provider request failed",provider,http_status:result.status,detail:result.body},502);return json({provider,query,result_count:normalized.length,results:normalized,policy:{durable_storage:false,reference_only:true,automatic_promotion:false}});
});