import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
function fromJson(n:string,k:string){try{return JSON.parse(Deno.env.get(n)||"{}")[k]||"";}catch{return "";}}
const ANON=Deno.env.get("SUPABASE_ANON_KEY")||fromJson("SUPABASE_PUBLISHABLE_KEYS","default");
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||fromJson("SUPABASE_SECRET_KEYS","default");
function json(b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
function env(n:string){return(Deno.env.get(n)||"").trim();} function txt(v:unknown){return v==null?"":String(v).trim();} function num(v:unknown){const x=Number(v);return Number.isFinite(x)?x:null;}
type P="mappls_reference"|"geoapify_reference"|"kakao_maps_reference"|"mapbox_reference";
const cfg:Record<P,string>={mappls_reference:"MAPPLS_STATIC_KEY",geoapify_reference:"GEOAPIFY_API_KEY",kakao_maps_reference:"KAKAO_REST_API_KEY",mapbox_reference:"MAPBOX_ACCESS_TOKEN"};
async function getj(url:string,init?:RequestInit){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(url,{...init,signal:c.signal,headers:{"accept":"application/json",...(init?.headers||{})}});const raw=await r.text();let body:any;try{body=raw?JSON.parse(raw):null}catch{body={raw:raw.slice(0,300)}}return{ok:r.ok,status:r.status,body};}finally{clearTimeout(t);}}
function normalize(p:P,b:any){
 if(p==="geoapify_reference")return(Array.isArray(b?.features)?b.features:[]).slice(0,8).map((f:any)=>({provider:p,external_ref:txt(f?.properties?.place_id),name:txt(f?.properties?.name||f?.properties?.formatted),address:txt(f?.properties?.formatted),lat:num(f?.properties?.lat??f?.geometry?.coordinates?.[1]),lng:num(f?.properties?.lon??f?.geometry?.coordinates?.[0]),category:txt(f?.properties?.result_type)}));
 if(p==="kakao_maps_reference")return(Array.isArray(b?.documents)?b.documents:[]).slice(0,8).map((d:any)=>({provider:p,external_ref:txt(d?.id),name:txt(d?.place_name||d?.address_name),address:txt(d?.road_address_name||d?.address_name),lat:num(d?.y),lng:num(d?.x),category:txt(d?.category_group_name||d?.category_name)}));
 if(p==="mapbox_reference")return(Array.isArray(b?.features)?b.features:[]).slice(0,8).map((f:any)=>({provider:p,external_ref:txt(f?.id||f?.properties?.mapbox_id),name:txt(f?.properties?.name||f?.properties?.full_address||f?.place_name),address:txt(f?.properties?.full_address||f?.properties?.place_formatted||f?.place_name),lat:num(f?.geometry?.coordinates?.[1]),lng:num(f?.geometry?.coordinates?.[0]),category:txt(f?.properties?.feature_type)}));
 return(Array.isArray(b?.suggestedLocations)?b.suggestedLocations:[]).slice(0,8).map((d:any)=>({provider:p,external_ref:txt(d?.eLoc||d?.mapplsPin),name:txt(d?.placeName),address:txt(d?.placeAddress),lat:num(d?.latitude??d?.lat),lng:num(d?.longitude??d?.lng),category:txt(d?.type)}));
}
async function query(p:P,q:string,key:string,lat:number|null,lng:number|null,region:string){
 if(p==="geoapify_reference"){const u=new URL("https://api.geoapify.com/v1/geocode/search");u.searchParams.set("text",q);u.searchParams.set("limit","8");u.searchParams.set("format","geojson");u.searchParams.set("apiKey",key);if(lat!==null&&lng!==null)u.searchParams.set("bias",`proximity:${lng},${lat}`);return getj(u.toString());}
 if(p==="kakao_maps_reference"){const u=new URL("https://dapi.kakao.com/v2/local/search/keyword.json");u.searchParams.set("query",q);u.searchParams.set("size","8");if(lat!==null&&lng!==null){u.searchParams.set("x",String(lng));u.searchParams.set("y",String(lat));u.searchParams.set("radius","20000")}return getj(u.toString(),{headers:{Authorization:`KakaoAK ${key}`}});}
 if(p==="mapbox_reference"){const u=new URL("https://api.mapbox.com/search/geocode/v6/forward");u.searchParams.set("q",q);u.searchParams.set("limit","8");u.searchParams.set("access_token",key);if(lat!==null&&lng!==null)u.searchParams.set("proximity",`${lng},${lat}`);return getj(u.toString());}
 const u=new URL("https://search.mappls.com/search/places/textsearch/json");u.searchParams.set("query",q);u.searchParams.set("access_token",key);if(region)u.searchParams.set("region",region);if(lat!==null&&lng!==null)u.searchParams.set("location",`${lat},${lng}`);return getj(u.toString());
}
Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return json({error:"POST required"},405);if(!ANON||!SERVICE)return json({error:"Supabase keys unavailable"},500);
 const auth=req.headers.get("authorization")||"";const user=createClient(SUPABASE_URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const service=createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false}});
 const {data:{user:id}}=await user.auth.getUser();if(!id)return json({error:"Authenticated AFAT identity required"},401);
 const perms=await Promise.all([user.rpc("afat_has_permission",{p_permission_key:"map.evidence.review",p_company_id:null}),user.rpc("afat_has_permission",{p_permission_key:"planning.aggregate.view",p_company_id:null}),user.rpc("afat_has_permission",{p_permission_key:"system.configure",p_company_id:null})]);if(!perms.some(x=>x.data===true))return json({error:"Source federation authority required"},403);
 const body=await req.json().catch(()=>({})),action=txt(body.action||"status"),cityKey=txt(body.city_key||"cm-yaounde").toLowerCase();
 const {data:city}=await service.from("afat_city_profiles").select("id,city_name,country_code").eq("city_key",cityKey).eq("status","active").maybeSingle();if(!city)return json({error:"Active city profile required"},404);
 const {data:plans}=await service.from("afat_city_source_plans").select("source_key,plan_state,metadata").eq("city_profile_id",city.id).in("source_key",Object.keys(cfg));
 const enabled=new Map((plans||[]).map((x:any)=>[x.source_key,x]));
 if(action==="status"){const providers=(Object.keys(cfg) as P[]).map(p=>({provider:p,credential_env:cfg[p],configured:!!env(cfg[p]),city_state:enabled.get(p)?.plan_state||"unplanned",run_policy:enabled.get(p)?.metadata?.run_policy||"eligible"}));return json({city_key:cityKey,providers});}
 if(action==="probe"){const out:any[]=[];for(const p of Object.keys(cfg) as P[]){const plan:any=enabled.get(p);if(plan?.plan_state==="disabled"||plan?.metadata?.run_policy==="do_not_run_for_city"){out.push({provider:p,skipped:true,reason:"irrelevant_for_city"});continue;}const key=env(cfg[p]);if(!key){out.push({provider:p,configured:false,ok:false,reason:"missing_credential"});continue;}const r=await query(p,city.city_name,key,null,null,String(city.country_code||"").toUpperCase());const results=normalize(p,r.body);out.push({provider:p,configured:true,ok:r.ok,http_status:r.status,result_count:results.length});await service.from("afat_city_source_plans").update({last_run_at:new Date().toISOString(),last_success_at:r.ok?new Date().toISOString():undefined,last_result:{probe:true,http_status:r.status,result_count:results.length,checked_at:new Date().toISOString(),storage_policy:"reference_ephemeral_only"},plan_state:r.ok?"ready":"error",updated_at:new Date().toISOString()}).eq("city_profile_id",city.id).eq("source_key",p);}return json({city_key:cityKey,providers:out});}
 if(action!=="search")return json({error:"action must be status, probe or search"},400);
 const p=txt(body.provider) as P;if(!(p in cfg))return json({error:"Unsupported provider"},400);const plan:any=enabled.get(p);if(plan?.plan_state==="disabled"||plan?.metadata?.run_policy==="do_not_run_for_city")return json({error:"Provider is disabled for this city",provider:p},409);
 const key=env(cfg[p]);if(!key)return json({error:"Provider credential is not configured",provider:p},409);const q=txt(body.query).slice(0,160);if(q.length<2)return json({error:"query must contain at least 2 characters"},400);
 const lat=num(body.lat),lng=num(body.lng),region=txt(body.region||city.country_code).toUpperCase().slice(0,3);const r=await query(p,q,key,lat,lng,region),results=normalize(p,r.body);
 await service.from("afat_city_source_plans").update({last_run_at:new Date().toISOString(),last_success_at:r.ok?new Date().toISOString():undefined,last_result:{http_status:r.status,result_count:results.length,checked_at:new Date().toISOString(),storage_policy:"reference_ephemeral_only"},plan_state:r.ok?"ready":"error",updated_at:new Date().toISOString()}).eq("city_profile_id",city.id).eq("source_key",p);
 if(!r.ok)return json({error:"Provider request failed",provider:p,http_status:r.status,detail:r.body},502);return json({provider:p,query:q,result_count:results.length,results,policy:{durable_storage:false,reference_only:true,automatic_promotion:false}});
});