import express, { Request, Response } from 'express';
import { supabase } from '../infra/supabase';
import { requireAuthRole } from './routes';

const router = express.Router();
const PAYMENT_STATES = new Set(['pending','cash_due','mobile_money_pending','paid','failed','waived']);

async function participant(assignmentId:string, profileId:string, role:string){
 const {data:assignment,error}=await supabase.from('dispatch_assignments').select('id,booking_id,operator_id,dispatcher_id,status').eq('id',assignmentId).maybeSingle(); if(error) throw error; if(!assignment) return {assignment:null,allowed:false};
 let allowed=['admin','planner'].includes(role)||assignment.operator_id===profileId||assignment.dispatcher_id===profileId;
 if(!allowed&&assignment.booking_id){const {data:b,error:e}=await supabase.from('bookings').select('passenger_id').eq('id',assignment.booking_id).maybeSingle();if(e)throw e;allowed=b?.passenger_id===profileId;}
 return {assignment,allowed};
}
router.get('/dispatch/:assignmentId/closure',async(req:Request,res:Response)=>{const access=await requireAuthRole(req,res);if(!access)return;try{const id=String(req.params.assignmentId||'');const {assignment,allowed}=await participant(id,access.profile.id,String(access.profile.role||'').toLowerCase());if(!assignment)return res.status(404).json({error:'Dispatch assignment not found.'});if(!allowed)return res.status(403).json({error:'Forbidden'});const {data,error}=await supabase.from('afat_journey_closures').select('*').eq('dispatch_assignment_id',id).maybeSingle();if(error)throw error;return res.json({closure:data||null});}catch(e:any){return res.status(500).json({error:e?.message||'Journey closure unavailable.'});}});
router.post('/dispatch/:assignmentId/closure',async(req:Request,res:Response)=>{const access=await requireAuthRole(req,res);if(!access)return;try{const id=String(req.params.assignmentId||'');const {assignment,allowed}=await participant(id,access.profile.id,String(access.profile.role||'').toLowerCase());if(!assignment)return res.status(404).json({error:'Dispatch assignment not found.'});if(!allowed)return res.status(403).json({error:'Forbidden'});if(!['completed','disputed'].includes(assignment.status))return res.status(409).json({error:'Journey must be completed or disputed before closure.'});const payment_state=String(req.body?.payment_state||'pending').toLowerCase();if(!PAYMENT_STATES.has(payment_state))return res.status(400).json({error:'Invalid payment_state.'});const rating=req.body?.rating==null?null:Number(req.body.rating);if(rating!=null&&(!Number.isInteger(rating)||rating<1||rating>5))return res.status(400).json({error:'rating must be 1-5.'});const receipt_number=`AFAT-${id.slice(0,8).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`;const payload={dispatch_assignment_id:id,booking_id:assignment.booking_id,payment_state,payment_reference:req.body?.payment_reference||null,proof_reference:req.body?.proof_reference||null,receipt_number,rating,dispute_reason:req.body?.dispute_reason||null,closed_by:access.profile.id,updated_at:new Date().toISOString()};const {data,error}=await supabase.from('afat_journey_closures').upsert(payload,{onConflict:'dispatch_assignment_id'}).select('*').single();if(error)throw error;return res.json({closure:data,provider_live:false,payment_truth:payment_state});}catch(e:any){return res.status(500).json({error:e?.message||'Journey closure failed.'});}});
export default router;
