import React, { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, ArrowRight, Bell, Building2, Car, CheckCircle2, Clock3,
  FileCheck, Gauge, Landmark, Layers3, LogOut, MapPin, Navigation2, Radio,
  RefreshCw, Route, Search, ShieldCheck, UserCircle, Users, Wallet,
} from 'lucide-react';
import {
  createPassageIntent, fetchActiveDispatches, fetchComplianceRadar, fetchDemandRadar,
  fetchLiveMapOps, fetchMobilityMapFeed, fetchOpsReportCenter, fetchParticipantDispatches, fetchPassageIntents,
  fetchPublicPartnerConditions, supabase, updatePassageIntentStatus,
} from '../../supabaseClient';
import { AFATLogo } from './AFATLogo';
import { InteractiveMap } from './InteractiveMap';
import { PassagePlanner } from '../commuter/PassagePlanner';
import { PassengerJourneyContinuity } from '../commuter/PassengerJourneyContinuity';
import { OperatorMissionLifecycle } from '../operator/OperatorMissionLifecycle';
import { ROLE_FLOW } from '../../utils/roleWorkspace';

export type AdaptiveWorkspaceRole = 'commuter' | 'operator' | 'organization' | 'government' | 'planner' | 'admin';
type WorkspaceTab = 'home' | 'bookings' | 'notifications' | 'profile';
type LiveFeed = { incidents: any[]; tracks: any[]; checkpoints: any[] };

type Props = {
  role: AdaptiveWorkspaceRole;
  profile: any;
  membership?: any;
  activeTab?: WorkspaceTab;
  onNavigate: (tab: WorkspaceTab) => void;
  onSignOut: () => void;
};

const EMPTY_LIVE: LiveFeed = { incidents: [], tracks: [], checkpoints: [] };

const ROLE_META: Record<AdaptiveWorkspaceRole, { label: string; eyebrow: string; promise: string; accent: string; icon: React.ElementType }> = {
  commuter: { label: 'Passenger', eyebrow: 'Move safely', promise: 'Plan, request and follow one real journey without invented fares, ETAs or availability.', accent: 'text-blue-300', icon: Navigation2 },
  operator: { label: 'Operator', eyebrow: 'Deliver service', promise: 'Control availability, receive verified demand and move each mission through pickup, journey and closure.', accent: 'text-emerald-300', icon: Gauge },
  organization: { label: 'Organisation', eyebrow: 'Run your fleet', promise: 'Manage your own people, vehicles and compliance evidence without crossing into planner or admin authority.', accent: 'text-cyan-300', icon: Building2 },
  government: { label: 'Public Partner', eyebrow: 'Coordinate mobility', promise: 'Use privacy-safe, mandate-scoped movement evidence for accountable public response.', accent: 'text-teal-300', icon: Landmark },
  planner: { label: 'Planner', eyebrow: 'Operate the city', promise: 'Turn validated movement evidence into dispatch, recovery and measured interventions.', accent: 'text-violet-300', icon: Layers3 },
  admin: { label: 'Admin', eyebrow: 'Protect the system', promise: 'Govern identity, roles, compliance and platform integrity without taking planner decisions.', accent: 'text-rose-300', icon: ShieldCheck },
};

const TAB_COPY: Record<AdaptiveWorkspaceRole, Record<Exclude<WorkspaceTab, 'home'>, { title: string; description: string; empty: string }>> = {
  commuter: {
    bookings: { title: 'My journeys', description: 'Requests, assigned service, pickup, trip, closure and receipt live in one passenger timeline.', empty: 'No journey exists yet. Create a passage from Home to start.' },
    notifications: { title: 'Journey safety', description: 'Only route, pickup and safety information that affects your movement appears here.', empty: 'No route-relevant safety notice is active.' },
    profile: { title: 'Passenger identity', description: 'Identity and preferences remain passenger-scoped.', empty: '' },
  },
  operator: {
    bookings: { title: 'Mission control', description: 'Verified demand becomes an operator mission with clear next actions.', empty: 'No verified mission is waiting for this operator.' },
    notifications: { title: 'Service alerts', description: 'Disruptions and operating conditions connected to active work.', empty: 'No operator alert requires attention.' },
    profile: { title: 'Operator authority', description: 'Approval and vehicle state determine whether service can go online.', empty: '' },
  },
  planner: {
    bookings: { title: 'Dispatch board', description: 'Every intervention stays connected to evidence, owner, state and outcome.', empty: 'No active dispatch intervention is open.' },
    notifications: { title: 'Movement failures', description: 'Validated conditions requiring operational attention.', empty: 'No validated movement failure requires action.' },
    profile: { title: 'Planner authority', description: 'Planning scope stays separate from platform administration.', empty: '' },
  },
  organization: {
    bookings: { title: 'People and fleet', description: 'Operate only assets and members owned by this organisation.', empty: 'No owned fleet activity is visible yet.' },
    notifications: { title: 'Compliance readiness', description: 'Submission, review and approval remain different states.', empty: 'No organisation exception requires attention.' },
    profile: { title: 'Organisation record', description: 'Registration and membership boundaries stay explicit.', empty: '' },
  },
  government: {
    bookings: { title: 'Evidence register', description: 'Aggregated public mobility conditions without passenger or operator personal data.', empty: 'No validated public condition is in scope.' },
    notifications: { title: 'Response room', description: 'Coordinate only within the approved public mandate.', empty: 'No public response is currently required.' },
    profile: { title: 'Public mandate', description: 'Jurisdiction and access boundaries remain explicit.', empty: '' },
  },
  admin: {
    bookings: { title: 'Authority queue', description: 'Identity, privilege and compliance decisions remain auditable.', empty: 'No governance decision is waiting.' },
    notifications: { title: 'System integrity', description: 'Operational exceptions without mixing Admin and Planner authority.', empty: 'No platform integrity exception is open.' },
    profile: { title: 'Admin identity', description: 'Privileged actions remain attributable and reviewable.', empty: '' },
  },
};

function Surface({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <section className={`rounded-2xl border border-white/10 bg-white/[0.035] shadow-[0_24px_80px_rgba(0,0,0,0.18)] ${className}`}>{children}</section>;
}

function StatusPill({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'good' | 'warn' | 'bad' }) {
  const cls = tone === 'good' ? 'border-emerald-400/25 bg-emerald-400/10 text-emerald-200' : tone === 'warn' ? 'border-amber-400/25 bg-amber-400/10 text-amber-100' : tone === 'bad' ? 'border-red-400/25 bg-red-400/10 text-red-100' : 'border-white/10 bg-white/5 text-white/55';
  return <span className={`inline-flex rounded-full border px-3 py-1.5 text-[9px] font-black uppercase tracking-[0.18em] ${cls}`}>{children}</span>;
}

function WorkspaceHeader({ role, profile, onSignOut, loading, onRefresh }: { role: AdaptiveWorkspaceRole; profile: any; onSignOut: () => void; loading: boolean; onRefresh: () => void }) {
  const meta = ROLE_META[role];
  return <header className="sticky top-0 z-[900] border-b border-white/10 bg-[#050812]/92 px-4 py-3 backdrop-blur-2xl sm:px-7">
    <div className="mx-auto flex max-w-[1540px] items-center justify-between gap-4">
      <div className="flex min-w-0 items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-cyan-300/15 bg-cyan-400/10"><AFATLogo className="h-6 w-6 text-cyan-100" /></div><div className="min-w-0"><div className="flex items-center gap-2"><p className="text-base font-black">AFAT</p><StatusPill>{meta.label}</StatusPill></div><p className="truncate text-[9px] font-black uppercase tracking-[0.18em] text-white/30">African Movement Operating System</p></div></div>
      <div className="hidden min-w-0 flex-1 justify-center px-6 lg:flex"><div className="flex w-full max-w-xl items-center gap-3 rounded-xl border border-white/10 bg-black/20 px-4 py-3"><Search className="h-4 w-4 text-white/30" /><span className="truncate text-xs text-white/35">Search places, journeys, vehicles, evidence or decisions</span></div></div>
      <div className="flex items-center gap-2"><button type="button" onClick={onRefresh} aria-label="Refresh live workspace" className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 bg-white/5 text-white/55"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button><div className="hidden text-right sm:block"><p className="max-w-40 truncate text-xs font-black">{profile?.full_name || profile?.email || 'AFAT member'}</p><p className={`text-[9px] font-black uppercase tracking-wider ${meta.accent}`}>{meta.label}</p></div><button type="button" onClick={onSignOut} aria-label="Sign out" className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 bg-white/5 text-white/55"><LogOut className="h-4 w-4" /></button></div>
    </div>
  </header>;
}

function RoleFlow({ role, activeTab, onNavigate }: { role: AdaptiveWorkspaceRole; activeTab: WorkspaceTab; onNavigate: Props['onNavigate'] }) {
  const tabs: WorkspaceTab[] = ['home', 'bookings', 'notifications', 'profile'];
  return <div className="grid grid-cols-4 gap-2">{ROLE_FLOW[role].map((label, i) => <button key={label} type="button" onClick={() => onNavigate(tabs[i])} className={`min-h-14 rounded-xl border px-3 py-2 text-left transition ${activeTab === tabs[i] ? 'border-cyan-300/30 bg-cyan-400/10 text-white' : 'border-white/10 bg-black/15 text-white/38 hover:bg-white/5'}`}><span className="block text-[8px] font-black uppercase tracking-widest text-white/25">0{i + 1}</span><span className="mt-1 block text-[10px] font-black uppercase sm:text-xs">{label}</span></button>)}</div>;
}

function MapPanel({ role, live }: { role: AdaptiveWorkspaceRole; live: LiveFeed }) {
  const mapRole = role === 'admin' ? 'admin' : ['planner', 'government', 'organization'].includes(role) ? 'planner' : role;
  return <InteractiveMap role={mapRole as any} mapMode={role === 'commuter' ? 'standard' : 'intel'} incidents={live.incidents} tracks={live.tracks} checkpoints={live.checkpoints} realtimeOverlay={['operator', 'organization', 'planner', 'admin'].includes(role)} showInformal={role !== 'commuter'} />;
}

function RealityBar({ live, loading, errors }: { live: LiveFeed; loading: boolean; errors: string[] }) {
  const records = live.incidents.length + live.tracks.length + live.checkpoints.length;
  return <div className="flex flex-wrap items-center gap-2"><StatusPill tone={loading ? 'warn' : errors.length ? 'warn' : 'good'}>{loading ? 'Refreshing live services' : errors.length ? 'Partial live service' : 'Live services connected'}</StatusPill><StatusPill>{records} map records</StatusPill><StatusPill>{live.incidents.length} conditions</StatusPill><StatusPill>{live.tracks.length} moving assets</StatusPill><StatusPill>{live.checkpoints.length} meeting points</StatusPill></div>;
}

function PassengerHome({ profile, live, currentDispatch, onNavigate, onChanged }: { profile: any; live: LiveFeed; currentDispatch: any | null; onNavigate: Props['onNavigate']; onChanged: () => void }) {
  const [origin, setOrigin] = useState(profile?.preferred_zone || 'My current location');
  const [destination, setDestination] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [notice, setNotice] = useState('');
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); if (!profile?.id || !destination.trim()) return;
    setSubmitting(true); setNotice('');
    const { data, error } = await createPassageIntent({ passenger_id: profile.id, origin_text: origin.trim() || 'Current location', destination_text: destination.trim(), metadata: { source: 'passenger_workspace', city: profile?.preferred_city || null } });
    setSubmitting(false);
    if (error) setNotice(`Passage request failed: ${error.message}`); else setNotice(`Passage ${String(data?.passage?.id || data?.id || '').slice(0, 8) || 'request'} is live. AFAT is resolving verified service and a safe meeting point.`);
  };
  return <div className="grid gap-5 xl:grid-cols-[0.72fr_1.28fr]">
    <div className="space-y-5"><PassengerJourneyContinuity assignment={currentDispatch} onChanged={onChanged} /><Surface className="overflow-hidden bg-gradient-to-br from-blue-500/[0.14] via-cyan-400/[0.045] to-transparent p-6 sm:p-8"><p className="text-[10px] font-black uppercase tracking-[0.25em] text-blue-300/70">Passenger mission</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Where are you going?</h1><p className="mt-3 text-sm leading-6 text-white/50">Start with a real destination. AFAT reveals only service, fare and ETA evidence that actually exists.</p><form onSubmit={submit} className="mt-7 space-y-3"><label className="flex min-h-14 items-center gap-3 rounded-xl border border-white/10 bg-black/25 px-4"><MapPin className="h-4 w-4 text-emerald-300" /><input value={origin} onChange={e => setOrigin(e.target.value)} className="w-full bg-transparent text-sm font-bold outline-none" /></label><label className="flex min-h-14 items-center gap-3 rounded-xl border border-white/10 bg-black/25 px-4"><Search className="h-4 w-4 text-blue-300" /><input value={destination} onChange={e => setDestination(e.target.value)} placeholder="Destination or landmark" className="w-full bg-transparent text-sm font-bold outline-none placeholder:text-white/25" /></label><button disabled={!destination.trim() || submitting || !profile?.id} className="flex min-h-14 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-400 px-5 text-sm font-black disabled:opacity-40">{submitting ? 'Creating passage…' : 'Plan safe passage'} <ArrowRight className="h-4 w-4" /></button></form>{notice && <p className="mt-4 rounded-xl border border-white/10 bg-black/25 p-4 text-xs font-bold text-white/65">{notice}</p>}<button onClick={() => onNavigate('bookings')} className="mt-4 min-h-11 w-full rounded-xl border border-white/10 bg-white/5 text-xs font-black">Open journey timeline</button></Surface><Surface className="p-5"><div className="grid grid-cols-3 gap-3"><Metric icon={MapPin} label="Meeting points" value={live.checkpoints.length} /><Metric icon={Car} label="Visible supply" value={live.tracks.length} /><Metric icon={ShieldCheck} label="Conditions" value={live.incidents.length} /></div></Surface></div>
    <div className="space-y-5"><PassagePlanner profile={profile} originText={origin} initialDestination={destination} onPassageCreated={() => onNavigate('bookings')} /><div className="min-h-[430px]"><MapPanel role="commuter" live={live} /></div></div>
  </div>;
}

function Metric({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: React.ReactNode }) { return <div className="rounded-xl border border-white/10 bg-black/20 p-4"><Icon className="h-4 w-4 text-cyan-200" /><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-[8px] font-black uppercase tracking-wider text-white/30">{label}</p></div>; }

function OperatorHome({ profile, live, missions, currentDispatch, onNavigate, onChanged }: { profile: any; live: LiveFeed; missions: any[]; currentDispatch: any | null; onNavigate: Props['onNavigate']; onChanged: () => void }) {
  const [vehicle, setVehicle] = useState<any>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const mission = missions[0];
  useEffect(() => { if (!profile?.id) return; let active = true; supabase.from('vehicles').select('id, plate_number, type, status, is_available').eq('operator_id', profile.id).order('created_at', { ascending: false }).limit(1).maybeSingle().then(({ data, error }) => { if (!active) return; setVehicle(data || null); if (error) setNotice(error.message); }); return () => { active = false; }; }, [profile?.id]);
  const toggleOnline = async () => { if (!vehicle?.id) return setNotice('An approved vehicle is required before going online.'); setBusy(true); const next = !vehicle.is_available; const { error } = await supabase.from('vehicles').update({ is_available: next }).eq('id', vehicle.id); setBusy(false); if (error) setNotice(error.message); else { setVehicle((v: any) => ({ ...v, is_available: next })); setNotice(next ? 'Operator is online for verified demand.' : 'Operator is offline.'); } };
  const accept = async () => { if (!mission?.id || !profile?.id) return; setBusy(true); const { error } = await updatePassageIntentStatus(mission.id, { status: 'driver_acknowledged', operator_id: profile.id }); setBusy(false); setNotice(error ? error.message : 'Mission accepted. Pickup and passenger tracking can now progress.'); if (!error) onChanged(); };
  return <div className="grid gap-5 xl:grid-cols-[0.74fr_1.26fr]"><div className="space-y-5"><OperatorMissionLifecycle assignment={currentDispatch} onChanged={onChanged} /><Surface className="bg-gradient-to-br from-emerald-500/[0.13] to-transparent p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-emerald-300/70">Operator control</p><h1 className="mt-2 text-3xl font-black">{vehicle?.is_available ? 'Ready for verified demand' : 'Service is offline'}</h1><p className="mt-2 text-xs text-white/45">{vehicle ? `${vehicle.plate_number || 'Plate pending'} · ${vehicle.type || 'vehicle'} · ${vehicle.status || 'reviewed'}` : 'No approved vehicle is attached.'}</p></div><button onClick={toggleOnline} disabled={busy || !vehicle} className={`min-h-11 rounded-xl px-5 text-xs font-black disabled:opacity-35 ${vehicle?.is_available ? 'bg-emerald-400 text-slate-950' : 'border border-white/10 bg-white/5'}`}>{vehicle?.is_available ? 'Online' : 'Go online'}</button></div><div className="mt-6 grid grid-cols-2 gap-3"><Metric icon={Radio} label="Verified requests" value={missions.length} /><Metric icon={Car} label="Network vehicles" value={live.tracks.length} /></div></Surface><Surface className="p-5"><p className="text-[9px] font-black uppercase tracking-widest text-white/35">Next verified mission</p><h2 className="mt-2 text-xl font-black">{mission?.destination_text || 'No open request'}</h2><p className="mt-2 text-sm text-white/45">{mission ? `${mission.origin_text || 'Origin pending'} → ${mission.destination_text || 'Destination pending'}` : 'AFAT will show only a real eligible request.'}</p><div className="mt-4 grid grid-cols-2 gap-3"><Metric icon={MapPin} label="Meeting point" value={mission?.meeting_point_text || mission?.origin_text || '—'} /><Metric icon={Wallet} label="Trusted fare" value={mission?.fare_amount ? `${mission.fare_amount} ${mission.currency || 'XAF'}` : 'Awaiting quote'} /><Metric icon={Clock3} label="Mission state" value={mission?.status ? String(mission.status).replace(/_/g, ' ') : '—'} /><Metric icon={ShieldCheck} label="Evidence" value={mission?.id ? 'Verified' : '—'} /></div><div className="mt-5 flex gap-2"><button onClick={accept} disabled={!vehicle?.is_available || !mission?.id || busy || Boolean(currentDispatch && !['completed','cancelled','expired','declined','no_show'].includes(String(currentDispatch.status || '').toLowerCase()))} className="min-h-12 flex-1 rounded-xl bg-emerald-400 px-4 text-xs font-black text-slate-950 disabled:opacity-35">Accept request</button><button onClick={() => onNavigate('bookings')} className="min-h-12 rounded-xl border border-white/10 px-4 text-xs font-black">Mission queue</button></div>{notice && <p className="mt-3 rounded-xl border border-white/10 bg-black/20 p-3 text-xs text-white/60">{notice}</p>}</Surface></div><div className="min-h-[620px]"><MapPanel role="operator" live={live} /></div></div>;
}

function PlannerHome({ live, operations, onNavigate }: { live: LiveFeed; operations: any; onNavigate: Props['onNavigate'] }) {
  const situations = live.incidents.slice(0, 6); const dispatches = operations?.dispatches || []; const pressure = operations?.demand?.summary?.pressure ?? 0; const recommendation = operations?.demand?.summary?.recommendation || 'No live recommendation';
  return <div className="grid gap-5 xl:grid-cols-[0.58fr_1.08fr_0.72fr]"><Surface className="p-5"><p className="text-[10px] font-black uppercase tracking-widest text-violet-300">Validated situation queue</p><div className="mt-4 space-y-3">{situations.map((item: any, i: number) => <article key={item.id || i} className="rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-sm font-black">{item.name || item.type || 'Movement condition'}</p><p className="mt-2 text-[10px] uppercase text-white/35">{item.status || 'validated'} · severity {item.severity || '—'}</p></article>)}{!situations.length && <p className="rounded-xl border border-dashed border-white/15 p-6 text-sm text-white/35">No validated movement failure is in the live queue.</p>}</div></Surface><div className="min-h-[620px]"><MapPanel role="planner" live={live} /></div><Surface className="p-5"><p className="text-[10px] font-black uppercase tracking-widest text-violet-300">City operations posture</p><h2 className="mt-2 text-2xl font-black">Decide from current evidence</h2><div className="mt-5 grid grid-cols-2 gap-3"><Metric icon={Activity} label="Demand pressure" value={pressure} /><Metric icon={Radio} label="Active dispatches" value={dispatches.length} /></div><div className="mt-3 rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-[9px] font-black uppercase text-white/35">Engine recommendation</p><p className="mt-2 text-sm font-bold capitalize">{String(recommendation).replace(/_/g, ' ')}</p></div><div className="mt-3 rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-[9px] font-black uppercase text-white/35">Evidence provenance</p><p className="mt-2 text-xs leading-5 text-white/55">{live.incidents.length + live.tracks.length + live.checkpoints.length} live records. Unknown values remain unknown.</p></div><button onClick={() => onNavigate('bookings')} className="mt-5 min-h-12 w-full rounded-xl bg-violet-500 text-xs font-black">Open dispatch board</button><button onClick={() => onNavigate('notifications')} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 text-xs font-black text-white/70">Review disruptions</button></Surface><Surface className="xl:col-span-3 p-4"><p className="mb-3 text-[9px] font-black uppercase tracking-widest text-white/35">Intervention lifecycle</p><div className="grid grid-cols-5 gap-2">{['Detect', 'Simulate', 'Approve', 'Dispatch', 'Measure'].map((step, i) => <div key={step} className={`rounded-xl border p-3 ${i === 0 && situations.length ? 'border-violet-300/30 bg-violet-500/10' : i === 3 && dispatches.length ? 'border-cyan-300/30 bg-cyan-500/10' : 'border-white/10 bg-black/20'}`}><span className="text-[8px] font-black text-white/30">0{i + 1}</span><p className="mt-1 text-[9px] font-black uppercase sm:text-xs">{step}</p></div>)}</div></Surface></div>;
}

function ScopedHome({ role, membership, live, operations, onNavigate }: { role: 'organization' | 'government' | 'admin'; membership: any; live: LiveFeed; operations: any; onNavigate: Props['onNavigate'] }) {
  const meta = ROLE_META[role]; const Icon = meta.icon; const title = role === 'organization' ? membership?.companies?.name || 'Organisation operations' : role === 'government' ? membership?.partner?.name || 'Public mobility coordination' : 'Platform governance'; const attention = role === 'admin' ? (operations?.reports?.reports?.length || 0) + (operations?.compliance?.summary?.overdue || 0) : live.incidents.length;
  return <div className="grid gap-5 xl:grid-cols-[0.72fr_1.28fr]"><Surface className="p-6 sm:p-8"><Icon className={`h-7 w-7 ${meta.accent}`} /><p className={`mt-5 text-[10px] font-black uppercase tracking-[0.25em] ${meta.accent}`}>{meta.eyebrow}</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">{title}</h1><p className="mt-3 text-sm leading-6 text-white/50">{meta.promise}</p><div className="mt-6 rounded-xl border border-amber-300/20 bg-amber-400/10 p-4"><div className="flex items-center gap-3"><AlertTriangle className="h-5 w-5 text-amber-200" /><div><p className="text-sm font-black">{attention ? `${attention} live item${attention === 1 ? '' : 's'} need attention` : 'No urgent exception returned'}</p><p className="mt-1 text-xs text-white/45">Derived from current AFAT service evidence.</p></div></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={() => onNavigate('bookings')} className="rounded-xl border border-cyan-300/20 bg-cyan-400/10 p-5 text-left"><Users className="h-5 w-5 text-cyan-200" /><span className="mt-4 block text-base font-black">{role === 'admin' ? 'Authority queue' : role === 'government' ? 'Evidence register' : 'People and fleet'}</span><span className="mt-2 block text-xs text-white/45">Open the role-owned operational queue.</span></button><button onClick={() => onNavigate('notifications')} className="rounded-xl border border-amber-300/20 bg-amber-400/10 p-5 text-left"><FileCheck className="h-5 w-5 text-amber-200" /><span className="mt-4 block text-base font-black">{role === 'admin' ? 'Integrity exceptions' : role === 'government' ? 'Response room' : 'Compliance readiness'}</span><span className="mt-2 block text-xs text-white/45">Keep evidence, review and approval states explicit.</span></button></div></Surface><div className="min-h-[540px]"><MapPanel role={role} live={live} /></div></div>;
}

function TabCanvas({ role, activeTab, profile, membership, live, missions, operations, onSignOut }: { role: AdaptiveWorkspaceRole; activeTab: Exclude<WorkspaceTab, 'home'>; profile: any; membership: any; live: LiveFeed; missions: any[]; operations: any; onSignOut: () => void }) {
  const copy = TAB_COPY[role][activeTab]; const items = activeTab === 'bookings' ? role === 'operator' ? missions : role === 'planner' ? operations?.dispatches || [] : live.tracks : activeTab === 'notifications' ? live.incidents : []; const identity = role === 'organization' ? membership?.companies : role === 'government' ? membership?.partner : profile;
  return <div className="grid gap-5 xl:grid-cols-[0.68fr_1.32fr]"><Surface className="p-6 sm:p-8"><p className={`text-[10px] font-black uppercase tracking-[0.25em] ${ROLE_META[role].accent}`}>{ROLE_META[role].label}</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">{copy.title}</h1><p className="mt-3 text-sm leading-6 text-white/50">{copy.description}</p>{activeTab === 'profile' ? <div className="mt-6 space-y-3"><div className="rounded-xl border border-white/10 bg-black/20 p-4"><UserCircle className="h-5 w-5 text-cyan-200" /><p className="mt-3 text-base font-black">{identity?.name || identity?.full_name || profile?.email || 'Verified AFAT identity'}</p><p className="mt-1 text-xs text-white/40">Status: {identity?.status || membership?.status || profile?.status || 'active'}</p></div><button onClick={onSignOut} className="min-h-12 w-full rounded-xl border border-white/10 bg-white/5 text-xs font-black">Sign out securely</button></div> : <div className="mt-6 grid grid-cols-3 gap-3"><Metric icon={Radio} label="Queue" value={items.length} /><Metric icon={MapPin} label="Meeting points" value={live.checkpoints.length} /><Metric icon={Bell} label="Conditions" value={live.incidents.length} /></div>}</Surface><Surface className="p-5"><h2 className="text-sm font-black uppercase tracking-wider">Live {activeTab === 'profile' ? 'access boundary' : 'operational records'}</h2>{activeTab === 'profile' ? <div className="mt-5 rounded-xl border border-cyan-300/15 bg-cyan-400/[0.04] p-5 text-sm leading-7 text-white/55">Changing workspace never silently changes an approved role, organisation, jurisdiction or authority.</div> : <div className="mt-4 space-y-3">{items.slice(0, 10).map((item: any, i: number) => <article key={item.id || i} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 text-emerald-300" /><div><p className="text-sm font-black">{item.destination_text || item.name || item.type || item.status || `${ROLE_META[role].label} record`}</p><p className="mt-1 text-xs text-white/40">{item.origin_text || item.description || item.status || 'Live AFAT service record'}</p></div></div></article>)}{!items.length && <p className="rounded-xl border border-dashed border-white/15 p-8 text-center text-sm text-white/35">{copy.empty}</p>}</div>}</Surface></div>;
}

export function AdaptiveRoleHome({ role, profile, membership, activeTab = 'home', onNavigate, onSignOut }: Props) {
  const [live, setLive] = useState<LiveFeed>(EMPTY_LIVE); const [missions, setMissions] = useState<any[]>([]); const [operations, setOperations] = useState<any>({}); const [loading, setLoading] = useState(true); const [serviceErrors, setServiceErrors] = useState<string[]>([]); const [refreshKey, setRefreshKey] = useState(0);
  useEffect(() => { let active = true; const hydrate = async () => { setLoading(true); const errors: string[] = []; const city = profile?.preferred_city || profile?.base_city || 'cameroon'; try { const mapResult = role === 'government' ? await fetchPublicPartnerConditions(city) : ['planner', 'admin'].includes(role) ? await fetchLiveMapOps(city) : await fetchMobilityMapFeed(city); if (!active) return; if (mapResult.data) setLive({ incidents: mapResult.data.incidents || [], tracks: mapResult.data.vehicles || [], checkpoints: mapResult.data.checkpoints || mapResult.data.addresses || [] }); if (mapResult.error) errors.push(`Map services: ${mapResult.error.message}`); if (role === 'commuter' || role === 'operator') { const participantDispatches = await fetchParticipantDispatches({ include_terminal: true, limit: 20 }); if (participantDispatches.error) errors.push(`Journey continuity: ${participantDispatches.error.message}`); if (active) setOperations((current: any) => ({ ...current, participantDispatches: participantDispatches.data?.dispatches || [] })); } if (role === 'operator') { const requests = await fetchPassageIntents({ status: 'requested' }); if (active) setMissions(requests.data?.passages || []); if (requests.error) errors.push(`Mission queue: ${requests.error.message}`); } if (role === 'planner') { const [demand, dispatches] = await Promise.all([fetchDemandRadar(), fetchActiveDispatches()]); if (active) setOperations({ demand: demand.data, dispatches: dispatches.data?.dispatches || [] }); if (demand.error) errors.push(`Demand radar: ${demand.error.message}`); if (dispatches.error) errors.push(`Dispatch board: ${dispatches.error.message}`); } if (role === 'admin') { const [reports, compliance] = await Promise.all([fetchOpsReportCenter(), fetchComplianceRadar()]); if (active) setOperations({ reports: reports.data, compliance: compliance.data }); if (reports.error) errors.push(`Reports: ${reports.error.message}`); if (compliance.error) errors.push(`Compliance: ${compliance.error.message}`); } } catch (error: any) { errors.push(error?.message || 'AFAT live services could not be refreshed.'); } if (active) { setServiceErrors(errors); setLoading(false); } }; hydrate(); return () => { active = false; }; }, [role, profile?.id, profile?.preferred_city, profile?.base_city, refreshKey]);
  const meta = ROLE_META[role]; const Icon = meta.icon; const refresh = () => setRefreshKey(v => v + 1); const participantDispatches = operations?.participantDispatches || []; const currentDispatch = participantDispatches.find((item: any) => ['queued','offered','accepted','assigned','en_route','arrived','pickup_verified','in_journey','reassigned','emergency','disputed'].includes(String(item.status || '').toLowerCase())) || participantDispatches[0] || null; const home = useMemo(() => { if (role === 'commuter') return <PassengerHome profile={profile} live={live} currentDispatch={currentDispatch} onNavigate={onNavigate} onChanged={refresh} />; if (role === 'operator') return <OperatorHome profile={profile} live={live} missions={missions} currentDispatch={currentDispatch} onNavigate={onNavigate} onChanged={refresh} />; if (role === 'planner') return <PlannerHome live={live} operations={operations} onNavigate={onNavigate} />; if (role === 'organization' || role === 'government' || role === 'admin') return <ScopedHome role={role} membership={membership} live={live} operations={operations} onNavigate={onNavigate} />; return null; }, [role, profile, membership, live, missions, operations, onNavigate]);
  return <div className="min-h-screen bg-[#050812] text-white"><WorkspaceHeader role={role} profile={profile} onSignOut={onSignOut} loading={loading} onRefresh={refresh} /><main className="mx-auto max-w-[1540px] px-4 pb-28 pt-5 sm:px-7"><div className="mb-5 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2"><Icon className={`h-4 w-4 ${meta.accent}`} /><p className={`text-[10px] font-black uppercase tracking-[0.25em] ${meta.accent}`}>{meta.eyebrow}</p></div><h2 className="mt-2 text-2xl font-black tracking-tight">{meta.label} workspace</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/45">{meta.promise}</p></div><RealityBar live={live} loading={loading} errors={serviceErrors} /></div><RoleFlow role={role} activeTab={activeTab} onNavigate={onNavigate} />{serviceErrors.length > 0 && <div className="mb-5 rounded-xl border border-amber-400/20 bg-amber-400/10 p-4"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-200" /><div><p className="text-xs font-black text-amber-100">AFAT is operating with partial live data.</p><p className="mt-1 text-xs leading-5 text-white/45">{serviceErrors.join(' · ')}</p></div></div></div>}<div className="mt-5">{activeTab === 'home' ? home : <TabCanvas role={role} activeTab={activeTab as Exclude<WorkspaceTab, 'home'>} profile={profile} membership={membership} live={live} missions={missions} operations={operations} onSignOut={onSignOut} />}</div></main></div>;
}
