create table if not exists public.afat_operation_metrics (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  operation text not null check (operation in ('route','atlas_nearby','place_search','place_viewport','nearby_supply','offline_pack','service_request','navigation_sync','city_ingest')),
  city_key text,mode text,duration_ms integer not null check (duration_ms between 0 and 300000),
  outcome text not null check (outcome in ('success','unavailable','error','offline','cancelled')),
  error_class text,cache_state text check (cache_state is null or cache_state in ('hit','miss','coalesced','network')),
  result_count integer check (result_count is null or result_count>=0),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);
create index if not exists afat_operation_metrics_time_idx on public.afat_operation_metrics(created_at desc);
create index if not exists afat_operation_metrics_operation_time_idx on public.afat_operation_metrics(operation,created_at desc);
create index if not exists afat_operation_metrics_city_operation_idx on public.afat_operation_metrics(city_key,operation,created_at desc);
alter table public.afat_operation_metrics enable row level security;
revoke all on public.afat_operation_metrics from anon,authenticated;grant select on public.afat_operation_metrics to authenticated;
drop policy if exists afat_operation_metrics_planner_read on public.afat_operation_metrics;
create policy afat_operation_metrics_planner_read on public.afat_operation_metrics for select to authenticated using (public.afat_has_permission('planning.aggregate.view') or public.afat_has_permission('system.configure'));
create or replace function public.afat_record_operation_metric(p_operation text,p_duration_ms integer,p_outcome text,p_city_key text default null,p_mode text default null,p_error_class text default null,p_cache_state text default null,p_result_count integer default null,p_metadata jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path='public','extensions','pg_catalog' as $$
declare v_uid uuid:=auth.uid();v_safe jsonb;
begin
 if p_operation not in ('route','atlas_nearby','place_search','place_viewport','nearby_supply','offline_pack','service_request','navigation_sync','city_ingest') then return;end if;
 if p_outcome not in ('success','unavailable','error','offline','cancelled') then return;end if;
 if p_duration_ms is null or p_duration_ms<0 or p_duration_ms>300000 then return;end if;
 v_safe:=jsonb_strip_nulls(jsonb_build_object('surface',left(coalesce(p_metadata->>'surface',''),40),'route_status',left(coalesce(p_metadata->>'route_status',''),40),'network',left(coalesce(p_metadata->>'network',''),20)));
 insert into public.afat_operation_metrics(profile_id,operation,city_key,mode,duration_ms,outcome,error_class,cache_state,result_count,metadata)
 values(v_uid,p_operation,nullif(left(trim(coalesce(p_city_key,'')),80),''),nullif(left(trim(coalesce(p_mode,'')),30),''),p_duration_ms,p_outcome,nullif(left(trim(coalesce(p_error_class,'')),80),''),p_cache_state,p_result_count,v_safe);
end $$;
create or replace function public.afat_performance_snapshot(p_city_key text default null,p_hours integer default 24)
returns jsonb language plpgsql security definer set search_path='public','extensions','pg_catalog' as $$
declare v_uid uuid:=auth.uid();v_hours integer:=greatest(1,least(coalesce(p_hours,24),168));v_rows jsonb;
begin
 if v_uid is null then raise exception 'Authentication required';end if;
 if not(public.afat_has_permission('planning.aggregate.view') or public.afat_has_permission('system.configure')) then raise exception 'Planning permission required';end if;
 select coalesce(jsonb_agg(jsonb_build_object('operation',operation,'samples',samples,'success_rate_pct',success_rate_pct,'p50_ms',p50_ms,'p95_ms',p95_ms,'max_ms',max_ms,'cache_hit_rate_pct',cache_hit_rate_pct,'errors',errors) order by operation),'[]'::jsonb) into v_rows from(
 select operation,count(*)::int samples,round(100.0*count(*) filter(where outcome='success')/nullif(count(*),0),1) success_rate_pct,
 round(percentile_cont(0.5) within group(order by duration_ms))::int p50_ms,round(percentile_cont(0.95) within group(order by duration_ms))::int p95_ms,max(duration_ms)::int max_ms,
 round(100.0*count(*) filter(where cache_state='hit')/nullif(count(*) filter(where cache_state is not null),0),1) cache_hit_rate_pct,count(*) filter(where outcome='error')::int errors
 from public.afat_operation_metrics where created_at>=now()-make_interval(hours=>v_hours) and(p_city_key is null or city_key=p_city_key) group by operation)q;
 return jsonb_build_object('city_key',p_city_key,'window_hours',v_hours,'operations',v_rows,'privacy','no raw coordinates, search text or destination names','generated_at',now());
end $$;
create or replace function public.afat_purge_operation_metrics(p_retention_days integer default 14)
returns jsonb language plpgsql security definer set search_path='public','extensions','pg_catalog' as $$
declare v_days integer:=greatest(1,least(coalesce(p_retention_days,14),30));v_count integer;
begin delete from public.afat_operation_metrics where created_at<now()-make_interval(days=>v_days);get diagnostics v_count=row_count;return jsonb_build_object('deleted',v_count,'retention_days',v_days);end $$;
revoke all on function public.afat_record_operation_metric(text,integer,text,text,text,text,text,integer,jsonb) from public;
revoke all on function public.afat_performance_snapshot(text,integer) from public,anon;
revoke all on function public.afat_purge_operation_metrics(integer) from public,anon,authenticated;
grant execute on function public.afat_record_operation_metric(text,integer,text,text,text,text,text,integer,jsonb) to anon,authenticated;
grant execute on function public.afat_performance_snapshot(text,integer) to authenticated;
grant execute on function public.afat_purge_operation_metrics(integer) to service_role;
