-- TSIDKENU: Firm OS v1 MVP Schema
-- This schema establishes the Case Management Core, Billing, and Document Tracking.

-- 1. FIRMS & LAWYERS (The Users)
CREATE TABLE firms (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    country TEXT DEFAULT 'Cameroon',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE lawyers (
    id UUID PRIMARY KEY REFERENCES auth.users(id), -- Connects to Supabase Auth
    firm_id UUID REFERENCES firms(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    role TEXT CHECK (role IN ('Partner', 'Senior Associate', 'Junior Associate', 'Intern')),
    microsoft_graph_token TEXT, -- Encrypted token for their personal OneDrive
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. CASE MANAGEMENT CORE
CREATE TABLE matters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    firm_id UUID REFERENCES firms(id) ON DELETE CASCADE,
    lead_lawyer_id UUID REFERENCES lawyers(id),
    title TEXT NOT NULL,
    client_name TEXT NOT NULL,
    status TEXT CHECK (status IN ('Lead', 'Onboarding', 'Active', 'In Court', 'Closed')),
    risk_level TEXT CHECK (risk_level IN ('Low', 'Medium', 'High')),
    jurisdiction TEXT DEFAULT 'OHADA',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TASKS & DEADLINES (Coordination)
CREATE TABLE tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    matter_id UUID REFERENCES matters(id) ON DELETE CASCADE,
    assigned_to UUID REFERENCES lawyers(id),
    title TEXT NOT NULL,
    deadline TIMESTAMP WITH TIME ZONE,
    is_completed BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. DOCUMENT TRACKING (OneDrive Bridge & Analysis)
CREATE TABLE documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    matter_id UUID REFERENCES matters(id) ON DELETE CASCADE,
    uploaded_by UUID REFERENCES lawyers(id),
    title TEXT NOT NULL,
    onedrive_file_id TEXT, -- The ID from Microsoft Graph (if stored in OneDrive)
    ai_summary TEXT, -- Generated by Llama 3.3 / Qwen
    requires_compliance_audit BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. BASIC BILLING (Financial Pulse)
CREATE TABLE invoices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    matter_id UUID REFERENCES matters(id) ON DELETE CASCADE,
    amount_xaf DECIMAL NOT NULL,
    status TEXT CHECK (status IN ('Draft', 'Sent', 'Partial', 'Paid', 'Overdue')),
    due_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. OPENCLAW AGENT MEMORY (The Automation Log)
CREATE TABLE agent_activity_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    firm_id UUID REFERENCES firms(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL, -- e.g., 'scan_onedrive', 'audit_compliance'
    description TEXT NOT NULL,
    is_critical BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS (Row Level Security) Policies
-- (In production, these ensure a lawyer can only see their own firm's data)
ALTER TABLE matters ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Firms can only see their own matters" ON matters
    FOR ALL USING (firm_id = (SELECT firm_id FROM lawyers WHERE id = auth.uid()));
